image:
  file: .gitpod.Dockerfile

tasks:
- name: Start Couchbase
  before:  cd /opt/couchbase/ && ./start-cb.sh

# exposed ports
ports:
- port: 8091
  onOpen: open-preview
- port: 8092-10000
  onOpen: ignore

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
