image:
  file: .gitpod.Dockerfile

tasks:
- name: Start Couchbase
  before:  cd /opt/couchbase/ && ./start-cb.sh && sleep 10
- name: Init App
  init: echo "The Application is ready."

# exposed ports
ports:
- port: 8091
  onOpen: open-browser
- port: 8092-10000
  onOpen: ignore
- port: 4369
  onOpen: ignore

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
