
tasks:
- name: Couchbase
  init:  cd / && ./start-cb.sh

# exposed ports
ports:
- port: 8091
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
